import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: 'Drools',
    image: 'https://petmate-shop.netlify.app/images/drools-image.png',
    price: '250',
    discount: '10',
    rating: '3.8',
    description: 'For Adults 1.2Kg',
    categoryName: 'Dog-Food',
  },
  {
    _id: uuid(),
    title: 'Pedigree',
    image: 'https://petmate-shop.netlify.app/images/pedigree-image.png',
    price: '250',
    discount: '15',
    rating: '4.0',
    description: 'For Adults 1Kg',
    categoryName: 'Dog-Food',
  },
  {
    _id: uuid(),
    title: 'Arden Grange',
    image: './Assets/images/ardengrangefordog.jpg',
    price: '350',
    discount: '15',
    rating: '4.8',
    description: 'For Puppies 2Kg',
    categoryName: 'Dog-Food',
  },
  {
    _id: uuid(),
    title: 'Healthy Pet Food',
    image:
      './Assets/images/Himalaya-Healthy-Pet-Food-Chicken-Rice-Puppy-Food.jpg',
    price: '350',
    discount: '15',
    rating: '5.0',
    description: 'For Puppies 1.2Kg',
    categoryName: 'Dog-Food',
  },
  {
    _id: uuid(),
    title: 'Natures Gifts',
    image: './Assets/images/ardengrangefordog.jpg',
    price: '350',
    discount: '15',
    rating: '3.8',
    description: 'For Adults 6Kg',
    categoryName: 'Dog-Food',
  },
  {
    _id: uuid(),
    title: 'Purepet',
    image: 'https://petmate-shop.netlify.app/images/purepet-image.png',
    price: '200',
    discount: '25',
    rating: '4.8',
    description: 'Ocean Fish Adults 1.2Kg',
    categoryName: 'Cat-Food',
  },
  {
    _id: uuid(),
    title: 'Kit & Kaboodle',
    image: './Assets/images/kitandkaboodleforcats.jpg',
    price: '600',
    discount: '20',
    rating: '3.4',
    description: 'Ocean Fish Adults 5.9Kg',
    categoryName: 'Cat-Food',
  },
  {
    _id: uuid(),
    title: 'Meaoon',
    image: './Assets/images/maeoonforcats.jpg',
    price: '500',
    discount: '25',
    rating: '4.8',
    description: 'Chicken & Sea Food Adults 1.2Kg',
    categoryName: 'Cat-Food',
  },
  {
    _id: uuid(),
    title: 'Nutro',
    image: './Assets/images/nutroforcat.jpg',
    price: '400',
    discount: '10',
    rating: '3.8',
    description: 'Chicken & Brown Rice Adults 1.2Kg',
    categoryName: 'Cat-Food',
  },
  {
    _id: uuid(),
    title: 'Dino Flamingo',
    image: './Assets/images/DinoFlamingo.jpg',
    price: '100',
    discount: '10',
    rating: '4.8',
    description: 'For all Pets made with Cotton',
    categoryName: 'Toys',
  },
  {
    _id: uuid(),
    title: 'Duck',
    image: './Assets/images/duck.jpg',
    price: '150',
    discount: '10',
    rating: '3.8',
    description: 'For all Pets made with Plastic',
    categoryName: 'Toys',
  },
  {
    _id: uuid(),
    title: 'Jack Toy',
    image: './Assets/images/jacktoy.jpg',
    price: '400',
    discount: '20',
    rating: '4.8',
    description: 'For all Pets made with Plastic',
    categoryName: 'Toys',
  },
  {
    _id: uuid(),
    title: 'Rugby Ball',
    image: './Assets/images/rugbyball.jpg',
    price: '300',
    discount: '20',
    rating: '4.8',
    description: 'For all Pets made with Plastic',
    categoryName: 'Toys',
  },
  {
    _id: uuid(),
    title: 'SmartKat',
    image: './Assets/images/smartkat.jpg',
    price: '200',
    discount: '20',
    rating: '4.2',
    description: 'For Cats made with Plastic',
    categoryName: 'Toys',
  },
  {
    _id: uuid(),
    title: 'DumbBells',
    image: './Assets/images/wooddumbbell.jpg',
    price: '300',
    discount: '10',
    rating: '3.2',
    description: 'For Dogs made with Wood',
    categoryName: 'Toys',
  },
];
